spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/joke-app
    username : ${APPLICATION_DB_USERNAME}
    password: ${APPLICATION_DB_PASSWORD}

securetracktraining:
  jokeprovider:
    url: https://v2.jokeapi.dev/joke
    rate: 10000

